micronaut:
  application:
    name: corona-slack

jackson:
  propertyNamingStrategy: SNAKE_CASE


datasources:
  default:
    url: 'jdbc:h2:file:${H2_DB};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations



jooq:
  datasources:
    default:
      sql-dialect: 'H2'

